### ISSUE TITLE
Add Jax bindings

### ISSUE THREAD

**Issue by ceriottm** [lab-cosmo/sphericart#36]
Tagging @felixmusil who seemed interested. Challenge here would be to reuse as much as possible the CUDA code @nickjbrowning wrote for libtorch. The whole concept is to keep the codebase as compact as possible.

**Comment by felixmusil** [comment]
I looked into the details of how to extend JAX with custom [cpp and cuda](https://github.com/dfm/extending-jax) operations. 
From what I gather the heavy lifting consists in registering both the cpp and cuda code as `XLA custom` operations so that the operation can be jitted from the JAX side. On the cpp side, probably only some additional interface to follow the `XLA custom` op requirements is needed but the current cuda code depends on `torch` so I fear heavy refactoring would be required.

**Comment by ceriottm** [comment]
I agree. I think that we need to start a discussion with @nickjbrowning in this respect.

**Comment by nickjbrowning** [comment]
Hey @felixmusil !

I don't think it will be too tricky to separate out the CUDA code. As far as I can see we should be able to remove the torch dependencies and then provide two front-ends that wrap the PyTorch and XLA frontends separately. I'll be away next week but after that I can start looking into it when I'm back.

**Comment by felixmusil** [comment]
Perfect then I will try to get the CPP side of the Jax bindings working in the meantime.

**Comment by ceriottm** [comment]
I think the main issue will be packaging, but it's worth starting at least a draft PR
